language: java

services:
  - mongodb

notifications:
  irc:
    channels:
      - "irc.oftc.net#limesco-travis"
    template:
      - "%{branch}/%{commit} (#%{build_number} by %{author}): %{message} %{build_url}"

